version: '3'
services:
  dbt-bq-dtc:
    build:
      context: .
      target: dbt-bigquery
    image: dbt/bigquery
    volumes:
      - .:/usr/app
      - $HOME/.dbt/:/root/.dbt/
      - $HOME/.google/credentials/google_credentials.json:/.google/credentials/google_credentials.json
    network_mode: host
